### ISSUE TITLE
'dict' object has no attribute '______'

### ISSUE THREAD

**Issue by tux777** [cankatx/cstealer#12]
Line 264, your obfuscator is bad bro. You could at least test your project before committing it lmfao 😂

**Comment by cankatx** [comment]
My project is working, it doesn't matter this error shows up maybe you should at least test the project before opening issue lmfao 😂

**Comment by CactusHamster** [comment]
Doesn't obfuscation go against the point of keeping the project open-source anyways?

**Comment by cankatx** [comment]
thats how I find a solution to bypass anti-viruses

**Comment by CactusHamster** [comment]
@cankatx I am quite sure an antivirus would not decompile the bytecode in a pyinstaller executable, much less understand what it does.
