### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by cratern9602** [cankatx/cstealer#23]
If you get the discord grabber injected, where is the folder that the injection goes to. just so i can clear it rather than everytime i open discord it gives my info

**Comment by cankatx** [comment]
1. Go to "C:\Users\USERNAME\AppData\Local\Discord\app-1.0.9011\modules\discord_desktop_core-1\discord_desktop_core" path
2. Click edit "index.js" file
3. Delete everything inside of that file and replace with `module.exports = require('./core.asar');`
4. Save the index.js file and restart your Discord
